### ISSUE TITLE
bug: max_display_rows, max_width, max_col_width not  effect in settings

### ISSUE THREAD

**Issue by wubx** [datafuselabs/bendsql#217]
https://github.com/datafuselabs/bendsql/blob/main/cli/src/config.rs#L34-L41

```
cat ~/.config/bendsql/config.toml
[settings]
max_display_rows=1000
max_width=10000
max_col_width=1000
```
use:
```
show settings;
```
just only display 40 rows.
![img_v2_408a2ba2-622b-4d76-89eb-afe53c8d27dg](https://github.com/datafuselabs/bendsql/assets/320680/7d55beb9-4587-4025-905f-0ed08d243ffa)

![QHNvS7cvDf](https://github.com/datafuselabs/bendsql/assets/320680/49715779-10b5-4dba-810a-65dc7ca4963f)

None of them work. 
![image](https://github.com/datafuselabs/bendsql/assets/320680/c83624aa-1404-4389-8549-0150ad3cf09c)

**Comment by TCeason** [comment]
Got

**Comment by sundy-li** [comment]
https://github.com/datafuselabs/bendsql/blob/main/cli/src/config.rs#L106

This function is incomplete.

**Comment by wubx** [comment]
https://github.com/datafuselabs/bendsql/blob/main/cli/src/config.rs#L200

Can we change this value to biger ,like 10000 by default?
