### ISSUE TITLE
not return exit code as 1 on sql failed on one line execution

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/bendsql#226]
I have a CI job using bendsql in the databend-perf repo.

but it seems not return an exit code 1 on execution failed:

![Screenshot 2023-09-18 at 19 04 41](https://github.com/datafuselabs/bendsql/assets/129800/2fa0c455-a58c-44d1-9d04-6c0583e19588)

**Comment by everpcpc** [comment]
already fixed in https://github.com/datafuselabs/bendsql/pull/225
