### ISSUE TITLE
fest: keep the previous database when reconnecting

### ISSUE THREAD

**Issue by Dousir9** [datafuselabs/bendsql#258]
I was using the `tpcds` database, and when I reconnected to databend, I was switched to the default database, which was inconsistent with the behavior of mysql client.
<img width="883" alt="截屏2023-10-10 15 28 17" src="https://github.com/datafuselabs/bendsql/assets/54522439/30b01c2e-4bc1-4e77-9e6c-94b5f8019eca">

**Comment by everpcpc** [comment]
It seems to be a problem with flight sql.

**Comment by sundy-li** [comment]
are you using flight ? @Dousir9

**Comment by Dousir9** [comment]
> are you using flight ? @Dousir9 

Yes， the port I uesd is 8900.

**Comment by sundy-li** [comment]
There is no way to reconnect with the same database...
