### ISSUE TITLE
bendsql will hang for a while when connect to a started warehouse

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/bendsql#338]
Warehouse already running:
<img width="1000" alt="image" src="https://github.com/datafuselabs/bendsql/assets/172204/51d2b836-fffc-4d19-aa0a-874ecab5b8d9">

Connect to the warehouse using BendSQL(video):
https://github.com/datafuselabs/bendsql/assets/172204/733334f1-7b4c-44ec-b2ae-3c864bb53550

This will hang a while after connected to the warehouse:
```
Welcome to BendSQL 0.12.3-unknown.
Connecting to gw.aws-us-east-2.default.databend.com:443 as user bohu.
Connected to DatabendQuery v1.2.294-nightly-02630a4306(rust-1.75.0-nightly-2024-01-13T06:37:34.143688594Z)

--- hang a while
bohu@(bh-pr12977)/default>
```

**Comment by everpcpc** [comment]
It will run prompt sql to get keywords after connected https://github.com/datafuselabs/bendsql/blob/main/cli/src/session.rs#L71

**Comment by BohuTANG** [comment]
> It will run prompt sql to get keywords after connected https://github.com/datafuselabs/bendsql/blob/main/cli/src/session.rs#L71

I guess it should not so slow, it's almost 1 minutes each time, this is happens in the latest few versions, my old version(I forgot the number) does not has this issue.

**Comment by everpcpc** [comment]
We could run

```sql
select name from system.tables union all select name from system.columns union all select name from system.databases union all select name from system.functions;
```

manually to check if the query is too slow.

**Comment by BohuTANG** [comment]
> We could run
> 
> ```sql
> select name from system.tables union all select name from system.columns union all select name from system.databases union all select name from system.functions;
> ```
> 
> manually to check if the query is too slow.

Smart, I think this is the key point.
