### ISSUE TITLE
Add argument presign=auto/detect/on/off

### ISSUE THREAD

**Issue by everpcpc** [datafuselabs/bendsql#341]
auto: on with `Databend Cloud` and off with others

**Comment by flaneur2020** [comment]
i suppose that the backend can help pass some infomation to the client about having presign or not, without knowing it's Databend cloud or not.

**Comment by everpcpc** [comment]
> i suppose that the backend can help pass some infomation to the client about having presign or not, without knowing it's Databend cloud or not.

But this could not resolve network issues we've recently met.

**Comment by flaneur2020** [comment]
IMO the backend can tell the client the "suggested" way to pass data while some kind of handshaking, on deploy a self-hosted databend-query, we can have a config about the suggested data plane (presign or stream upload).

this handshaking info can also help passing some kind of metadata about the backend's version, and the client can raise an warning if it met an unsupported version.
