### ISSUE TITLE
`databend_driver::rows::RowIterator` which is not `Send`

### ISSUE THREAD

**Issue by attila-lin** [datafuselabs/bendsql#35]
When use the `databend-driver` with `poem`, it shows this error

```
error: future cannot be sent between threads safely
   --> src\api\query.rs:18:1
    |
18  | #[handler]
    | ^^^^^^^^^^ future created by async block is not `Send`
    |
    = help: the trait `Send` is not implemented for `(dyn Future<Output = Result<databend_client::response::QueryResponse, anyhow::Error>> + 'static)`
note: future is not `Send` as this value is used across an await
   --> src\db\db.rs:129:42
    |
128 |         let mut rows = self.conn.query_iter(&sql).await?;
    |             -------- has type `databend_driver::rows::RowIterator` which is not `Send`
129 |         while let Some(row) = rows.next().await {
    |                                          ^^^^^^ await occurs here, with `mut rows` maybe used later
...
135 |     }
    |     - `mut rows` is later dropped here
```

Any advice?

**Comment by attila-lin** [comment]
Hi! I tried 0.2.3.

It needs `mutable` to do `insert`. Might be good to hide the mutable?

**Comment by everpcpc** [comment]
Mutable is required by `FlightSQL` client, and also necessary for `RestAPI` client to keep connection session settings.
I think maybe most network client would require mutable, would that be a problem?

**Comment by attila-lin** [comment]
I used client like `mongodb`, [refs this link](https://docs.rs/mongodb/latest/mongodb/struct.Client.html).

It would be nice to make all operation do not need mutable, and the client is clonable(maybe hide with in a `Arc` point)?

Just some opinions.

**Comment by everpcpc** [comment]
Could you please check `0.2.11`?
