### ISSUE TITLE
no linux arm64 python bindings in pip

### ISSUE THREAD

**Issue by AndrewChubatiuk** [datafuselabs/bendsql#413]
Hey! Could you please explain why python bindings build for linux/arm64 is disabled?
https://github.com/datafuselabs/bendsql/blob/3ba9d1fe50e55c86182e5bc565036195c89cc512/.github/workflows/bindings.python.yml#L57

**Comment by everpcpc** [comment]
It depends on `ring` which could not build on the default `manylinux_2_17` with `maturin`.
