### ISSUE TITLE
 symbol not found in flat namespace '_PyPyBaseObject_Type'

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/bendsql#441]
0.17.2 works, but upgrade to 0.18.3 got:
```
ImportError: dlopen(/.../opt/anaconda3/envs/feature-store/lib/python3.10/site-packages/databend_driver/_[databend_driver.abi3.so](http://databend_driver.abi3.so/), 0x0002): symbol not found in flat namespace '_PyPyBaseObject_Type'
```

**Comment by everpcpc** [comment]
cannot reproduce

```
❯ docker run --net=host --rm --entrypoint=bash -it pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime
root@saki:/workspace# pip install databend-driver
Collecting databend-driver
  Downloading databend_driver-0.18.3-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Downloading databend_driver-0.18.3-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 3.5 MB/s eta 0:00:00
Installing collected packages: databend-driver
Successfully installed databend-driver-0.18.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@saki:/workspace# python
Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from databend_driver import BlockingDatabendClient
>>> client = BlockingDatabendClient('databend+http://root:root@localhost:8000/?sslmode=disable')
>>> import databend_driver
>>> print(databend_driver.__file__)
/opt/conda/lib/python3.10/site-packages/databend_driver/__init__.py
```

**Comment by rdonnelly3** [comment]
Also having these issues with my team.  We are on Macs (arm64).  Reproduced below:

`07-12-2024 11:18:27 AM in ~/test/test-databend-driver 
➜ python3 -m venv myenv

07-12-2024 11:18:47 AM in ~/test/test-databend-driver took 2.8s 
➜ source myenv/bin/activate

07-12-2024 11:19:37 AM in ~/test/test-databend-driver via myenv 
➜ pip install databend-driver
Looking in indexes: https://aws:****
Collecting databend-driver
  Using cached ****/databend-driver/0.18.3/databend_driver-0.18.3-cp37-abi3-macosx_11_0_arm64.whl (4.4 MB)
Installing collected packages: databend-driver
Successfully installed databend-driver-0.18.3

07-12-2024 11:20:21 AM in ~/test/test-databend-driver via myenv 
➜ python3
Python 3.10.14 (main, Jun 13 2024, 15:43:02) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from databend_driver import BlockingDatabendClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rdonnelly/test/test-databend-driver/myenv/lib/python3.10/site-packages/databend_driver/__init__.py", line 17, in <module>
    from ._databend_driver import *
ImportError: dlopen(/Users/rdonnelly/test/test-databend-driver/myenv/lib/python3.10/site-packages/databend_driver/_databend_driver.abi3.so, 0x0002): symbol not found in flat namespace '_PyPyBaseObject_Type'`

**Comment by everpcpc** [comment]
It seems to be a temporary build system problem, please upgrade the package to check if the problem still exists.

**Comment by rdonnelly3** [comment]
It is working now with version `databend-driver-0.19.2`
