### ISSUE TITLE
support multiline sql

### ISSUE THREAD

**Issue by l1t1** [datafuselabs/bendsql#78]
like `clickhouse client -mA`

**Comment by l1t1** [comment]
0.30 fixed
```
bendsql> select 1
    -> -4 a;

SELECT
  1 -4 a;

┌───────┐
│   a   │
│ Int16 │
├───────┤
│    -3 │
└───────┘

1 row in 0.024 sec. Processed 1 rows, 1B (41.52 rows/s, 41B/s)
```

**Comment by l1t1** [comment]
Ctrl D can exit now

**Comment by l1t1** [comment]
a bug.  when sql finished.  the process bar didn't disappear. 
WITH customer_total_return AS (
  SELECT
    sr_customer_sk AS ctr_customer_sk,
    sr_store_sk AS ctr_store_sk,
    sum(SR_FEE) AS ctr_total_return
  FROM
    store_returns,
    date_dim
  WHERE
    sr_returned_date_sk = d_date_sk
    AND d_year = 2000
  GROUP BY
    sr_customer_sk,
    sr_store_sk
)
SELECT
  c_customer_id
FROM
  customer_total_return ctr1,
  store,
  customer
WHERE
  ctr1.ctr_total_return > (
    SELECT
      avg(ctr_total_return) * 1.2
    FROM
      customer_total_return ctr2
    WHERE
      ctr1.ctr_store_sk = ctr2.ctr_store_sk
  )
  AND s_store_sk = ctr1.ctr_store_sk
  AND s_state = 'TN'
  AND ctr1.ctr_customer_sk = c_customer_sk
ORDER BY
  c_customer_id
LIMIT
  10;

⠁ [00:00:00] Processing 67.89 thousand/213.25 thousand (252.6 million rows/s), 1.82 MiB/┌──────────────────┐
│   c_customer_id  │
│      String      │
├──────────────────┤
│ AAAAAAAAAAFCAAAA │
│ AAAAAAAAAAKBAAAA │
│ AAAAAAAAAALBAAAA │
│ AAAAAAAAAANAAAAA │
│ AAAAAAAAABECAAAA │
│ AAAAAAAAABFAAAAA │
│ AAAAAAAAABGCAAAA │
│ AAAAAAAAABMAAAAA │
│ AAAAAAAAABNBAAAA │
│ AAAAAAAAACBBAAAA │
└──────────────────┘

10 rows in 0.282 sec. Processed 213.25 thousand rows, 208.25 KiB (756.54 thousand rows/s, 4.55 MiB/s)

bendsql>

**Comment by l1t1** [comment]
the format of clickhouse is thinner, it's more convenient for reading

ClickHouse local version 23.4.1.1073 (official build).

localhost.localdomain :) WITH customer_total_return AS
:-] (
:-] SELECT
:-] sr_customer_sk AS ctr_customer_sk,
:-] sr_store_sk AS ctr_store_sk,
:-] sum(sr_fee) AS ctr_total_return
:-] FROM file('t2/store_returns.parquet') AS store_returns, file('t2/date_dim.parquet') AS date_dim
:-] WHERE (sr_returned_date_sk = d_date_sk) AND (d_year = 2000)
:-] GROUP BY
:-] sr_customer_sk,
:-] sr_store_sk
:-] )
:-] SELECT c_customer_id
:-] FROM customer_total_return AS ctr1, file('t2/store.parquet') AS store, file('t2/customer.parquet') AS customer
:-] WHERE (ctr1.ctr_total_return > (
:-] SELECT avg(ctr_total_return) * 1.2
:-] FROM customer_total_return AS ctr2
:-] WHERE ctr1.ctr_store_sk = ctr2.ctr_store_sk
:-] )) AND (s_store_sk = ctr1.ctr_store_sk) AND (s_state = 'TN') AND (ctr1.ctr_customer_sk = c_customer_sk)
:-] ORDER BY c_customer_id ASC
:-] LIMIT 10;

WITH customer_total_return AS
    (
        SELECT
            sr_customer_sk AS ctr_customer_sk,
            sr_store_sk AS ctr_store_sk,
            sum(sr_fee) AS ctr_total_return
        FROM file('t2/store_returns.parquet') AS store_returns, file('t2/date_dim.parquet') AS date_dim
        WHERE (sr_returned_date_sk = d_date_sk) AND (d_year = 2000)
        GROUP BY
            sr_customer_sk,
            sr_store_sk
    )
SELECT c_customer_id
FROM customer_total_return AS ctr1, file('t2/store.parquet') AS store, file('t2/customer.parquet') AS customer
WHERE (ctr1.ctr_total_return > (
    SELECT avg(ctr_total_return) * 1.2
    FROM customer_total_return AS ctr2
    WHERE ctr1.ctr_store_sk = ctr2.ctr_store_sk
)) AND (s_store_sk = ctr1.ctr_store_sk) AND (s_state = 'TN') AND (ctr1.ctr_customer_sk = c_customer_sk)
ORDER BY c_customer_id ASC
LIMIT 10

**Comment by everpcpc** [comment]
> a bug. when sql finished. the process bar didn't disappear.

I can't reproduce this, would it happen every time?

> the format of clickhouse is thinner, it's more convenient for reading

What do you mean by `thinner`?

**Comment by l1t1** [comment]
1.yes
2.thinner means clickhouse didn't add new lines in the output sql, it only add indents.

**Comment by l1t1** [comment]
LIMIT
  1;

⠁ [00:00:00] Processing 67.89 thousand/213.25 thousand (126.54 million rows/s), 1.82 MiB┌──────────────────┐
│   c_customer_id  │
│      String      │
├──────────────────┤
│ AAAAAAAAAAFCAAAA │
└──────────────────┘

1 row in 0.721 sec. Processed 213.25 thousand rows, 208.25 KiB (295.65 thousand rows/s, 1.78 MiB/s)

**Comment by l1t1** [comment]
bendsql 0.31 fixed process bar
LIMIT
  1;

┌──────────────────┐
│   c_customer_id  │
│      String      │
├──────────────────┤
│ AAAAAAAAAAFCAAAA │
└──────────────────┘

1 row in 0.309 sec. Processed 213.25 thousand rows, 208.25 KiB (690.61 thousand rows/s, 4.15 MiB/s)
